- name: Create the database users
  mysql_user:
    name: "{{ item.name }}"
    password: "{{ item.password|default('foobar') }}"
    priv: "{{ item.priv|default('*.*:ALL') }}"
    state: present
    host: "{{ item.host | default('localhost') }}"
  with_items: mysql_users